Repository capnproto/go-capnp, pull requests merged in 2022-07, with the labels that each got.

#254 Fix broken implemenation of .Ack()
  server/server.go
  server/server_test.go
Labels: bug

#263 Export concrete arena types.
  message.go
Labels: enhancement

#264 Return error from generator.defineInterface
  capnpc-go/capnpc-go.go
Labels: bug

#266 Implement io.WriterTo for Message
  message.go
  message_test.go
Labels: enhancement

#265 Assorted clean-up tasks
  capnpc-go/capnpc-go_test.go
  encoding/text/marshal.go
  message_test.go
  packed/packed_test.go
Labels: cleanup

#261 Fix race conditions due to zero-copy semantics of pipe transport.
  rpc/bench_test.go
  rpc/level0_test.go
  rpc/level1_test.go
  rpc/transport/pipe.go
  rpc/transport/pipe_test.go
Labels: bug

#268 Bugfix/nil exc check fails
  rpc/answer.go
Labels: bug

#273 Remove server.Policy.
  capnpc-go/templates/interfaceServer
  example/hashes/go.mod
  example/hashes/hashesserver.go
  internal/aircraftlib/aircraft.capnp.go
  rpc/bench_test.go
  rpc/flow_test.go
  rpc/internal/testcapnp/test.capnp.go
  rpc/level0_test.go
  rpc/receiveranswer_test.go
  server/example_test.go
  server/server.go
  server/server_test.go
  std/capnp/persistent/persistent.capnp.go
Labels: cleanup
