Repository capnproto/go-capnp, pull requests merged in 2023-01, with the labels that each got.

#413 Minor style cleanup
  server/server.go
Labels: cleanup

#415 Minor cleanup.
  server/answer.go
Labels: cleanup

#422 Don't report nil error when shutting down import client.
  rpc/import.go
  rpc/rpc.go
Labels: bug

#430 Panic on flowcontrol deadlock
  flowcontrol/fixed.go
  flowcontrol/fixed_test.go
Labels: bug

#432 Add Release() method to capnp.Arena.
  integration_test.go
  message.go
Labels: enhancement
